source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def test_pods
    inherit! :search_paths
end

target 'Gitt' do
    pod 'RxSwift',                    '~> 5.0.1'              # Reactive/Functional Programming Framework
    pod 'RxCocoa',                    '~> 5.0.1'              # Reactive/Functional Programming Framework
    pod 'SnapKit',                    '~> 5.0.1'              # Constraint Programmatically.
    
    target 'GittTests' do
        test_pods
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.1'
        end
    end
end
